name: Run Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  run_databricks_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Databricks Notebook Run
        uses: steebchen/databricks-notebook-run-action@v1
        with:
          databricks-host: "https://dbc-0b374bc7-abe1.cloud.databricks.com/"
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          notebook-path: "/Users/merajalam@in.bosch.com/Notebook-V1'"
