name: Run Databricks Notebook

on:
  push:
    branches:
      - main

jobs:
  run_databricks_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Databricks Notebook
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_URL: "https://dbc-0b374bc7-abe1.cloud.databricks.com/"
          NOTEBOOK_ID: "/Users/merajalam@in.bosch.com/Notebook-V1"
        run: |
          curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" -H "Content-Type: application/json" -d '{"notebook_path": "$NOTEBOOK_ID"}' "$DATABRICKS_URL/jobs/runs/submit"
